image: node:18

stages:
  - publish

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - docker login --username iam --password $CLOUD_IAM_TOKEN cr.yandex
    - docker build --no-cache -t cr.yandex/$CLOUD_REGISTRY_ID/<APP>:<VERSION> -f Dockerfile .
    - docker push cr.yandex/$CLOUD_REGISTRY_ID/<APP>:<VERSION>

